apiVersion: config.openshift.io/v1
kind: OAuth
metadata:
  name: cluster
spec:
  identityProviders:
  - name: htpass-ex280
    mappingMethod: claim 
    type: HTPasswd
    htpasswd:
      fileData:
        name: htpass-idp-ex280
