apiVersion: v1
kind: PersistentVolume
metadata:
  name: gamma-pv
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Delete
  nfs:
    path: /exports-ocp4
    server: 192.168.50.254
  claimRef:
    name: gammapvc
    namespace: space
